version: "3"

services:

  cloud-weather-postgres:
    image: debezium/postgres:13-alpine
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_DATABASE=cloud_weather_precipitation_dev
    
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/data/db

volumes:
  postgres-data:
